import img1 from '../../client/src/resources/mockup.png';

const dummyData = [
  {
    id: 1,
    carImages: [img1],
    carName: 'Car Model 1',
    carDescription: 'Description for Car Model 1. Lorem ipsum dolor sit amet.',
    carYear: 2020,
    carMake: 'Brand 1',
    startingBid: 10000,
  },
  {
    id: 2,
    carImages: [img1],
    carName: 'Car Model 2',
    carDescription: 'Description for Car Model 2. Consectetur adipiscing elit.',
    carYear: 2018,
    carMake: 'Brand 2',
    startingBid: 12000,
  },
  {
    id: 3,
    carImages: [img1],
    carName: 'Car Model 3',
    carDescription: 'Description for Car Model 3. Sed do eiusmod tempor incididunt.',
    carYear: 2022,
    carMake: 'Brand 3',
    startingBid: 8000,
  },
  {
    id: 4,
    carImages: [img1],
    carName: 'Car Model 4',
    carDescription: 'Description for Car Model 4. Exercitation ullamco laboris nisi.',
    carYear: 2019,
    carMake: 'Brand 1',
    startingBid: 11000,
  },
  {
    id: 5,
    carImages: [img1],
    carName: 'Car Model 5',
    carDescription: 'Description for Car Model 5. Duis aute irure dolor in reprehenderit.',
    carYear: 2021,
    carMake: 'Brand 2',
    startingBid: 9500,
  },
  {
    id: 6,
    carImages: [img1],
    carName: 'Car Model 6',
    carDescription: 'Description for Car Model 6. Excepteur sint occaecat cupidatat non.',
    carYear: 2020,
    carMake: 'Brand 3',
    startingBid: 10500,
  },
  {
    id: 7,
    carImages: [img1],
    carName: 'Car Model 7',
    carDescription: 'Description for Car Model 7. Nemo enim ipsam voluptatem quia.',
    carYear: 2017,
    carMake: 'Brand 1',
    startingBid: 9500,
  },
  {
    id: 8,
    carImages: [img1],
    carName: 'Car Model 8',
    carDescription: 'Description for Car Model 8. Neque porro quisquam est.',
    carYear: 2022,
    carMake: 'Brand 2',
    startingBid: 12500,
  },
  {
    id: 9,
    carImages: [img1],
    carName: 'Car Model 9',
    carDescription: 'Description for Car Model 9. Temporibus autem quibusdam et.',
    carYear: 2019,
    carMake: 'Brand 3',
    startingBid: 10200,
  },
];

export default dummyData;
